- name: Installing nginx
  become: yes
  apt:
    name: nginx
    state: present
- name: Set up Nginx conf file
  template:
    src=nginx.conf.tbl
    dest=/etc/nginx/nginx.conf
  notify: restart nginx
